locals {
  generated_app_dir = "${path.module}/generated-repository-files"
}

resource "local_file" "generated_index_html" {
  filename = "${local.generated_app_dir}/index.html"

  content = <<-HTML
    <!DOCTYPE html>
    <html>
    <head>
      <title>AWS CI/CD Demo</title>
    </head>
    <body>
      <h1>Hello from AWS EC2!</h1>
      <p>This application was generated by Terraform.</p>
    </body>
    </html>
  HTML
}

resource "local_file" "generated_deploy_yaml" {
  filename = "${local.generated_app_dir}/.github/workflows/deploy.yaml"

  content = <<-YAML
    name: Deploy to EC2

    on:
      push:
        branches:
          - main

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ${var.aws_region}
      EC2_INSTANCE_ID: ${aws_instance.web.id}
      S3_BUCKET: ${aws_s3_bucket.deployment.bucket}

    jobs:
      deploy:
        runs-on: ubuntu-latest

        steps:
          # 1. Checkout source code
          - name: Checkout repository
            uses: actions/checkout@v5

          # 2. Authenticate to AWS using GitHub OIDC
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v6
            with:
              role-to-assume: ${aws_iam_role.github_actions.arn}
              aws-region: $${{ env.AWS_REGION }}

          # 3. Create deployment artifact
          - name: Create deployment artifact
            run: |
              zip "deploy-$${GITHUB_SHA}.zip" index.html

          # 4. Upload artifact to private S3 bucket
          - name: Upload artifact to S3
            run: |
              aws s3 cp \
                "deploy-$${GITHUB_SHA}.zip" \
                "s3://$${S3_BUCKET}/deployments/deploy-$${GITHUB_SHA}.zip"

          # 5. Send deployment command to EC2
          - name: Send deployment command
            id: ssm
            run: |
              COMMAND_ID=$(aws ssm send-command \
                --instance-ids "$${EC2_INSTANCE_ID}" \
                --document-name "AWS-RunShellScript" \
                --parameters "commands=[
                  \"aws s3 cp s3://$${S3_BUCKET}/deployments/deploy-$${GITHUB_SHA}.zip /tmp/deploy.zip\",
                  \"rm -rf /tmp/aws-cicd-demo\",
                  \"mkdir -p /tmp/aws-cicd-demo\",
                  \"unzip -o /tmp/deploy.zip -d /tmp/aws-cicd-demo\",
                  \"sudo cp /tmp/aws-cicd-demo/index.html /var/www/html/index.html\",
                  \"sudo systemctl restart httpd\"
                ]" \
                --query "Command.CommandId" \
                --output text)

              echo "COMMAND_ID=$COMMAND_ID" >> "$GITHUB_ENV"
              echo "SSM Command ID: $COMMAND_ID"

          # 6. Wait for deployment to finish
          - name: Wait for deployment
            run: |
              for i in {1..30}; do
                STATUS=$(aws ssm get-command-invocation \
                  --command-id "$${COMMAND_ID}" \
                  --instance-id "$${EC2_INSTANCE_ID}" \
                  --query "Status" \
                  --output text)

                echo "Deployment status: $STATUS"

                if [ "$STATUS" = "Success" ]; then
                  exit 0
                fi

                if [[ "$STATUS" =~ ^(Failed|Cancelled|TimedOut|Cancelling)$ ]]; then
                  echo "Deployment failed with status: $STATUS"
                  exit 1
                fi

                sleep 5
              done

              echo "Deployment timed out."
              exit 1

          # 7. Show deployment output
          - name: Show deployment output
            if: always()
            run: |
              aws ssm get-command-invocation \
                --command-id "$${COMMAND_ID}" \
                --instance-id "$${EC2_INSTANCE_ID}" \
                --query "{Status:Status,Output:StandardOutputContent,Error:StandardErrorContent}" \
                --output yaml
  YAML
}